global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tradingagents'
    static_configs:
      - targets: ['tradingagents-dashboard:8000']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    
  - job_name: 'tradingagents-health'
    static_configs:
      - targets: ['tradingagents-dashboard:8000']
    scrape_interval: 60s
    scrape_timeout: 15s
    metrics_path: '/health'
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s 